---
title: "02-pupil_size_peak_lmm"
output: html_document
date: "2023-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/alexander.lepauvre/Documents/GitHub/Reconstructed_time_analysis/bids")
library(lme4) # for the analysis
library(tidyverse) # needed for data manipulation.
library(emmeans)
library(lmerTest)
```

##  Setting the parameters
Setting the parameters. This is where the user can change the parameters if needed

```{r Housekeeping and parameters setting}
rm(list = ls())
bids_root <- getwd()
dir()

```

##  Loading the data
```{r Loading  data}
# Generate the file name:
full_path = file.path(bids_root, 'derivatives', 'pupil_latency', 'pupil_peak_latencies.csv')
data <- read.csv(full_path)
# Set the factors types:
data$duration<-as.factor(data$duration)
data$task<-as.factor(data$task)
data$sub_id<-as.factor(data$sub_id)
data$SOA_float<-as.numeric(data$SOA_float)
data$latency_aud<-as.numeric(data$latency_aud)
str(data)
```

## Full model
The full model is applied to all the data
```{r Full model:}
fullmodel <- lmer(formula = latency_aud ~ 1 + task * duration * lock * SOA_float + (1 | sub_id),
                  data = data)
summary(fullmodel)
anova(fullmodel)
```

## Onset model
The full model is applied to all the data
```{r Onset model:}
# Extract the onset data points only:
onset_data = data %>% filter(lock == "onset")

onset_model <- lmer(formula = latency_aud ~ 1 + duration * task * SOA_float + (1 + duration * task * SOA_float | sub_id),
                  data = onset_data)
summary(onset_model)
anova(onset_model)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
