---
title: "Simulate_data_ReconTime"
author: "Micha Engeser"
date: "2023-06-16"
output: html_document
---


```{r huosekeeping}
# clear workspace
rm(list = ls())

wd = 'C:/Users/micha.engeser/Documents/GitHub/Reconstructed_time_analysis'
setwd(wd)
dir()
```

# required packages

```{r packages} 

# get package manager package
if (!('pacman' %in% installed.packages()))
{install.packages("pacman")}
library(pacman)

# install all needed packages 

pacman::p_load('dplyr', 'ggdist', 'ggeffects', 'ggpubr', 'lme4', 'emmeans', 'rstatix', 'car', 'rsq', 'sjPlot', 'brms')

```

# stimulate the data

```{r}
# iniate table
sim_data_table = data.frame(matrix(ncol = 0, nrow = 1))
sim_data_table$sub_num = NaN
sim_data_table$SOA = NaN
sim_data_table$SOA_lock ='NaN'
sim_data_table$task_relevance = 'NaN'
sim_data_table$duration = NaN
sim_data_table$RT_aud = NaN
sim_data_table$iRT_aud = NaN
sim_data_table$iRT_vis = NaN
sim_data_table = sim_data_table[-c(1), ]

# define variable levels 
task_relevance_lvl = c('non-target', 'irrelevant')
SOA_lock_lvl = c('onset', 'offset')
SOA_lvl = c(0,0.116,0.232,0.466)
sub_num_lvl = 201:220
dur_lvl = c(0.5,1,1.5)

# loop through all combinations
for (o in sub_num_lvl){
  
  # add jitter for each subject
  sub_jitter = runif(n=1, min=-300, max=300)
  
  for (i in SOA_lvl){
    for (ii in SOA_lock_lvl) {
      for (iii in task_relevance_lvl) {
        for (iv in dur_lvl) {
        
# define RT for each combination        
RT_mean = 500        
if (ii == 'onset'){       
  if (i == 0){
    if (iii == 'non-target'){
      RT_mean = 800
    }else{
      RT_mean = 700
    }
  }else if (i == 0.116){
    if (iii == 'non-target'){
      RT_mean = 700
    }else{
      RT_mean = 600
    }
  }else if (i == 0.232){
    if (iii == 'non-target'){
      RT_mean = 600
    }
  }
}
       
if (iii == 'non-target'){
  iRT_vis_mean = 250
}else{
  iRT_vis_mean = 200
}
       
new_RT = rnorm(40, mean = RT_mean + sub_jitter, sd = 0)
new_iRTaud = rnorm(40, mean = 300 + sub_jitter, sd = 0)
new_iRTvis = rnorm(40, mean = iRT_vis_mean + sub_jitter, sd = 0) 

for (tr in 1:40){
sim_data_table = sim_data_table %>% add_row(sub_num = o,
  SOA = i,
  SOA_lock = ii,
  task_relevance = iii,
  duration = iv,
  RT_aud = new_RT[tr],
  iRT_aud = new_iRTaud[tr],
  iRT_vis = new_iRTvis[tr])
}        

}}}}}

sim_data_table = sim_data_table %>% mutate(onset_SOA = ifelse(SOA_lock == 'offset', SOA + duration, SOA))

```

# plotting RT by task-relevance

```{R}
n = length(sub_num_lvl)


# by task-relevance
SOA_SOA_lock_task_relevance_subj_data = sim_data_table %>% group_by(SOA, SOA_lock, task_relevance, sub_num) %>%
                                      summarise(RT_mean = mean(RT_aud, na.rm = TRUE))

SOA_SOA_lock_task_relevance_data = SOA_SOA_lock_task_relevance_subj_data %>%  group_by(SOA, SOA_lock, task_relevance) %>%
                                      summarise(mean_RT = mean(RT_mean, na.rm = TRUE),
                                                         sd_RT = sd(RT_mean, na.rm = TRUE),
                                                         sem_RT = sd_RT / sqrt(n))


p3 = ggplot(data=SOA_SOA_lock_task_relevance_data, aes(x=SOA*1000, y=mean_RT, group=interaction(task_relevance, SOA_lock), color=task_relevance, linetype = SOA_lock)) +
  geom_line()+
  geom_point()+
  ylim(c(400,900))+
  ylab("Auditory reaction time [ms]")+
  xlab('SOA [ms]')+
  scale_color_manual(values=c('blue', 'red'), name = 'Task Relevance', labels=c('task-relevant non-target', 'irrelevant'), breaks=c('non-target', 'irrelevant'))+
  scale_linetype_manual(values=c("solid", "dashed"), name = 'SOA time-locked to', breaks=c('onset', 'offset'))+
  theme_bw() +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(linetype = "solid"),
    panel.background = element_blank()) 
p3

# including RT vis 
SOA_SOA_lock_duration_subj_data4 = sim_data_table %>% group_by(onset_SOA,SOA_lock, duration, sub_num, task_relevance) %>%
                                      summarise(RT_mean = mean(RT_aud, na.rm = TRUE))

SOA_SOA_lock_duration_data4 = SOA_SOA_lock_duration_subj_data4 %>%  group_by(onset_SOA, SOA_lock,duration, task_relevance) %>%
                                      summarise(mean_RT = mean(RT_mean, na.rm = TRUE),
                                                         sd_RT = sd(RT_mean, na.rm = TRUE),
                                                         sem_RT = sd_RT / sqrt(n))


# remove NaNs from auditory responses
SOA_SOA_lock_duration_data4 = SOA_SOA_lock_duration_data4[!is.na(SOA_SOA_lock_duration_data4$mean_RT), ]

# define order
SOA_SOA_lock_duration_data4$task_relevance = factor(SOA_SOA_lock_duration_data4$task_relevance,
                                   levels = c('non-target', 'irrelevant'),
                                   labels = c('Relevant non-target', 'Irrelevant non-target'))


p24 = ggplot(data = SOA_SOA_lock_duration_data4, aes(x = onset_SOA * 1000, y = mean_RT, group = interaction(as.character(duration), SOA_lock), color = as.character(duration), linetype = SOA_lock)) +
  geom_point(size = 1.5) +
  geom_line(linewidth = 1) +
  facet_grid(. ~ task_relevance) +
  labs(title = "Predicted reaction time by task-relevance") +
  ylab("Auditory reaction time [ms]") +
  xlab('SOA to visual onset [ms]') +
  scale_color_manual(values = c('darkviolet', 'darkorange', 'darkred'),
                     name = 'Duration [ms]',
                     labels = c('500', '1000', '1500')) +
  scale_linetype_manual(values = c("solid", "longdash"),
                        name = 'SOA time-locked to',
                        breaks = c('onset', 'offset')) +
  theme_bw() +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(linetype = "solid"),
        panel.background = element_blank(),
        axis.text = element_text(color = "black", size = 15),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20, face="bold"),
        axis.title = element_text(size = 20, face="bold"),
        plot.title = element_text(size = 25, face="bold"),
        strip.text = element_text(size = 20))
p24
```

# plotting RT and iRT

```{R}

sim_iRT_data_table = sim_data_table %>% filter(SOA != 0.116)

SOA_SOA_lock_subj_data = sim_iRT_data_table %>% group_by(SOA, SOA_lock, sub_num) %>%
                                      summarise(RT_mean = mean(RT_aud, na.rm = TRUE),
                                                iRT_aud_mean = mean(iRT_aud, na.rm = TRUE),
                                                iRT_vis_mean = mean(iRT_vis, na.rm = TRUE))

SOA_SOA_lock_data = SOA_SOA_lock_subj_data %>%  group_by(SOA, SOA_lock) %>%
                                      summarise(mean_RT = mean(RT_mean, na.rm = TRUE),
                                                         sd_RT = sd(RT_mean, na.rm = TRUE),
                                                         sem_RT = sd_RT/sqrt(n),
                                                         mean_iRT_aud = mean(iRT_aud_mean, na.rm = TRUE),
                                                         sd_iRT_aud = sd(iRT_aud_mean, na.rm = TRUE),
                                                         sem_iRT_aud = sd_iRT_aud/sqrt(n),
                                                         mean_iRT_vis = mean(iRT_vis_mean, na.rm = TRUE),
                                                         sd_iRT_vis = sd(iRT_vis_mean, na.rm = TRUE),
                                                         sem_iRT_vis = sd_iRT_vis/sqrt(n))

p1 = ggplot(data=SOA_SOA_lock_data, aes(x=SOA*1000, y=mean_RT, group=SOA_lock, linetype = SOA_lock, color='objective RT')) +
  geom_line()+
  geom_point()+
  geom_line(aes(y=mean_iRT_aud, group=SOA_lock, linetype = SOA_lock, color='IT aud'))+
  geom_point(aes(y=mean_iRT_aud, group=SOA_lock, color='IT aud'))+
  geom_line(aes(y=mean_iRT_vis, group=SOA_lock, linetype = SOA_lock, color='IT vis'))+
  geom_point(aes(y=mean_iRT_vis, group=SOA_lock, color='IT vis'))+
  ylim(c(100,900))+
  ylab("Reaction time [ms]")+
  xlab('SOA [ms]')+
  scale_linetype_manual(values=c("solid", "dashed"), name = 'SOA time-locked to', breaks=c('onset', 'offset'))+
    theme_bw() +
  scale_color_manual(values=c('blue', 'red', 'darkgreen'), name = 'Measure', breaks=c('objective RT', 'IT aud', 'IT vis'))+
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(linetype = "solid"),
    panel.background = element_blank()) 
p1
```

# main plotting - iT 

```{R main_plotting_IT}

# p 1 by duration, extended time - by task relevance

SOA_SOA_lock_subj_data4 = sim_data_table %>% group_by(onset_SOA, SOA_lock, sub_num, task_relevance, duration) %>%
  summarise(RT_mean = mean(RT_aud, na.rm = TRUE),
            iT_aud_mean = mean(iRT_aud, na.rm = TRUE),
            iT_vis_mean = mean(iRT_vis, na.rm = TRUE))

# modify duration to show only one duration at the onset 
SOA_SOA_lock_subj_data4= SOA_SOA_lock_subj_data4 %>% mutate(duration = ifelse(SOA_lock == 'onset',0,duration))


SOA_SOA_lock_data4 = SOA_SOA_lock_subj_data4 %>%  group_by(onset_SOA, SOA_lock, task_relevance, duration) %>%
  summarise(mean_RT = mean(RT_mean, na.rm = TRUE),
            sd_RT = sd(RT_mean, na.rm = TRUE),
            sem_RT = sd_RT/sqrt(n),
            mean_iT_aud = mean(iT_aud_mean, na.rm = TRUE),
            sd_iT_aud = sd(iT_aud_mean, na.rm = TRUE),
            sem_iT_aud = sd_iT_aud/sqrt(n),
            mean_iT_vis = mean(iT_vis_mean, na.rm = TRUE),
            sd_iT_vis = sd(iT_vis_mean, na.rm = TRUE),
            sem_iT_vis = sd_iT_vis/sqrt(n))

# define order
SOA_SOA_lock_data4$task_relevance = factor(SOA_SOA_lock_data4$task_relevance , levels=c('non-target','irrelevant'))



# Define order and relabel levels for the task_relevance variable
SOA_SOA_lock_data4$task_relevance <- factor(SOA_SOA_lock_data4$task_relevance,
                                   levels = c('non-target', 'irrelevant'),
                                   labels = c('Relevant non-target', 'Irrelevant non-target'))



p13 = ggplot(data = SOA_SOA_lock_data4, aes(x = onset_SOA * 1000, y = mean_RT, group = interaction(as.character(duration), SOA_lock), linetype = SOA_lock, color = 'RT aud')) +
  geom_line(linewidth = 1) +
  geom_point(size = 1.5) +
  geom_line(aes(y = mean_iT_aud, linetype = SOA_lock, color = 'IT aud'), linewidth = 1) +
  geom_point(aes(y = mean_iT_aud, color = 'IT aud'), size = 1.5) +
  geom_line(aes(y = mean_iT_vis, linetype = SOA_lock, color = 'IT vis'), linewidth = 1) +
  geom_point(aes(y = mean_iT_vis, color = 'IT vis'), size = 1.5) +
  facet_grid(. ~ task_relevance) +
  labs(title = "Predicted reaction and decision time") +
  ylab("Time [ms]") +
  xlab('SOA to visual onset [ms]') +
  scale_linetype_manual(values = c("solid", "dashed"), name = 'SOA time-locked to', breaks = c('onset', 'offset')) +
  scale_color_manual(values = c('RT aud' = 'black', 'IT aud' = 'darkgreen', 'IT vis' = '#e600ac'),
                     name = 'Measure',
                     breaks = c('RT aud', 'IT aud', 'IT vis'),
                     labels = c(expression("RT"[aud]), expression("IT"[aud]~" "), expression("IT"[vis]~"  "))) +
  theme_bw() +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(linetype = "solid"),
        panel.background = element_blank(),
        axis.text = element_text(color = "black", size = 15),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20, face="bold"),
        axis.title = element_text(size = 20, face="bold"),
        plot.title = element_text(size = 25, face="bold"),
        strip.text = element_text(size = 20))
p13

```



# plotting RT and iRT

```{R}

sim_iRT_data_table = sim_data_table %>% filter(SOA != 0.116)

SOA_SOA_lock_subj_data = sim_iRT_data_table %>% group_by(SOA, SOA_lock, sub_num) %>%
                                      summarise(RT_mean = mean(RT_aud, na.rm = TRUE),
                                                iRT_aud_mean = mean(iRT_aud, na.rm = TRUE),
                                                iRT_vis_mean = mean(iRT_vis, na.rm = TRUE))

SOA_SOA_lock_data = SOA_SOA_lock_subj_data %>%  group_by(SOA, SOA_lock) %>%
                                      summarise(mean_RT = mean(RT_mean, na.rm = TRUE),
                                                         sd_RT = sd(RT_mean, na.rm = TRUE),
                                                         sem_RT = sd_RT/sqrt(n),
                                                         mean_iRT_aud = mean(iRT_aud_mean, na.rm = TRUE),
                                                         sd_iRT_aud = sd(iRT_aud_mean, na.rm = TRUE),
                                                         sem_iRT_aud = sd_iRT_aud/sqrt(n),
                                                         mean_iRT_vis = mean(iRT_vis_mean, na.rm = TRUE),
                                                         sd_iRT_vis = sd(iRT_vis_mean, na.rm = TRUE),
                                                         sem_iRT_vis = sd_iRT_vis/sqrt(n))

p1 = ggplot(data=SOA_SOA_lock_data, aes(x=SOA*1000, y=mean_RT, group=SOA_lock, linetype = SOA_lock, color='objective RT')) +
  geom_line()+
  geom_point()+
  geom_line(aes(y=mean_iRT_aud, group=SOA_lock, linetype = SOA_lock, color='IT aud'))+
  geom_point(aes(y=mean_iRT_aud, group=SOA_lock, color='IT aud'))+
  geom_line(aes(y=mean_iRT_vis, group=SOA_lock, linetype = SOA_lock, color='IT vis'))+
  geom_point(aes(y=mean_iRT_vis, group=SOA_lock, color='IT vis'))+
  ylim(c(100,900))+
  ylab("Reaction time [ms]")+
  xlab('SOA [ms]')+
  scale_linetype_manual(values=c("solid", "dashed"), name = 'SOA time-locked to', breaks=c('onset', 'offset'))+
    theme_bw() +
  scale_color_manual(values=c('blue', 'red', 'darkgreen'), name = 'Measure', breaks=c('objective RT', 'IT aud', 'IT vis'))+
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(linetype = "solid"),
    panel.background = element_blank()) 
p1
```
