---
title: "02-pupil_size_peak_lmm"
output: html_document
date: "2023-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4) # for the analysis
library(tidyverse) # needed for data manipulation.
library(emmeans)
library(lmerTest)
```

##  Setting the parameters
Setting the parameters. This is where the user can change the parameters if needed

```{r Housekeeping and parameters setting}
rm(list = ls())

# CHANGE THE BIDS ROOT TO MATCH YYOU
bids_root <- 'C:/Users/alexander.lepauvre/Documents/PhD/Reconstructed_Time/bids'
setwd(bids_root)
dir()

```

##  Loading the data
```{r Loading  data}
# Generate the file name:
full_path = file.path(bids_root, 'derivatives', 'blinks', 'group_level', 'data', 'blink_latencies.csv')
data <- read.csv(full_path)
```

## Full model
The full model is applied to all the data
```{r Full model:}
fullmodel <- lmer(formula = blink_latency ~ 1 + task_relevance * lock * soa + (1 + task_relevance * lock * soa | subject),
                  data = data)
summary(fullmodel)
anova(fullmodel)
```

## Onset model
The full model is applied to all the data
```{r Onset model:}
# Extract the onset data points only:
onset_data = data %>% filter(lock == "onset")

onset_model <- lmer(formula = blink_latency ~ 1 + task_relevance * soa + ( 1 + task_relevance * soa | subject),
                  data = onset_data)
summary(onset_model)
anova(onset_model)


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
